    ## app sg
    - name: Create security group
      openstack.cloud.security_group:
        cloud: kakao-cloud
        state: present
        name: "app-sg"
      register: security_group

    - name: Add security group rule to allow SSH
      openstack.cloud.security_group_rule:
        cloud: kakao-cloud
        security_group: "{{ security_group.security_group.id }}"
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        direction: ingress
        remote_ip_prefix: "{{bastion_floating_ip_var}}"

    - name: Add security group rule to allow HTTP
      openstack.cloud.security_group_rule:
        cloud: kakao-cloud
        security_group: "{{ security_group.security_group.id }}"
        protocol: tcp
        port_range_min: 80
        port_range_max: 80 
        direction: ingress
        remote_ip_prefix: "{{web_floating_ip_var}}"

    - name: Create boot volume
      openstack.cloud.volume:
        cloud: kakao-cloud
        state: present
        display_name: "app_volume"
        size: 50
        bootable: true
        image: "{{ vm.image_id }}"
      register: app_boot_volume

    - name: Create app-VM using boot volume
      openstack.cloud.server:
        state: present
        cloud: kakao-cloud
        name: "app-vm"
        flavor: "{{ vm.flavor }}"
        key_name: "{{ vm.key_pair }}"
        boot_volume: "{{ app_boot_volume.volume.id }}"
        security_groups:
          - "{{ security_group.security_group.id }}"
        nics:
          - net-id: "{{ app_network_id }}"
        wait: yes
      register: app_vm

    - name: Add app VM to inventory
      add_host:
        name: app-vm
        ansible_host: "{{app_fixed_ip_var}}"
        ansible_user: ubuntu
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@{{bastion_floating_ip_var}}"'


    - name: Remove specific IP from known_hosts
      lineinfile:
        path: "~/.ssh/known_hosts"
        state: absent
        regexp: "^{{ app_floating_ip.floating_ip.floating_ip_address }}[ ,]"

    - name: Wait for SSH to be available from local
      local_action:
        module: wait_for
        host: "{{ bastion_floating_ip.floating_ip.floating_ip_address }}"
        port: 22
        delay: 10
        timeout: 120
        state: started
      register: result
    
    
# - name: Initialize VM with application
#   hosts: web-vm
#   become: yes
#   tasks:
#     - name: Export APP_ENDPOINT environment variable
#       shell: |
#         export APP_ENDPOINT="{{ hostvars['app-vm']['ansible_host'] }}"
#       args:
#         executable: /bin/bash  

#     - import_tasks: web-init.yml