- name: Create resources and an OpenStack VM on Kakao Cloud
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create security group
      os_security_group:
        cloud: kakao-cloud
        state: present
        name: "my_security_group"
        description: "Security group for my VM"
      register: security_group

    # - name: Add security group rule to allow SSH
    #   os_security_group_rule:
    #     cloud: kakao-cloud
    #     security_group: "{{ security_group.security_group.id }}"
    #     protocol: tcp
    #     port_range_min: 22
    #     port_range_max: 22
    #     direction: ingress
    #     remote_ip_prefix: "0.0.0.0/0"

    - name: Create boot volume
      os_volume:
        cloud: kakao-cloud
        state: present
        display_name: "my_boot_volume"
        size: 50
        bootable: true
        image: d09c4a3f-4234-469e-8a00-6673dc4c4cee  # 이미지 ID를 여기에 추가해야 합니다
      register: boot_volume

    - name: Debug boot volume creation
      ansible.builtin.debug:
        var: boot_volume

    - name: Create VM using boot volume
      os_server:
        state: present
        cloud: kakao-cloud
        name: "kakaocloud-vm"
        flavor: "m2a.large"
        key_name: "ocean-keypair"
        boot_volume: "{{ boot_volume.volume.id }}"
        security_groups:
          - "{{ security_group.security_group.id }}"
        nics:
          - net-id: "482358ac-f4b4-4af2-9c08-1b8f63d59c94"
        wait: yes











##########
