- name: Delete resources created on OpenStack
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./variables.yml
  tasks:
    # - name: Find server by name
    #   openstack.cloud.server_info:
    #     cloud: kakao-cloud
    #     name: "kakaocloud-vm"
    #   register: found_servers

    # - name: Delete server if exists
    #   openstack.cloud.server:
    #     cloud: kakao-cloud
    #     state: absent
    #     server: "{{ found_servers.openstack_servers[0].id }}"
    #   when: found_servers.openstack_servers is defined and found_servers.openstack_servers | length > 0

    # - name: Find volume by name
    #   openstack.cloud.volume_info:
    #     cloud: kakao-cloud
    #     name: "web_volume"
    #   register: found_volumes

    # - name: Delete volume if exists
    #   openstack.cloud.volume:
    #     cloud: kakao-cloud
    #     state: absent
    #     volume: "{{ found_volumes.openstack_volumes[0].id }}"
    #   when: found_volumes.openstack_volumes is defined and found_volumes.openstack_volumes | length > 0

    # - name: Find floating IP
    #   openstack.cloud.floating_ip_info:
    #     cloud: kakao-cloud
    #   register: found_floating_ips

    # - name: Delete floating IP if exists
    #   openstack.cloud.floating_ip:
    #     cloud: kakao-cloud
    #     state:  absent 
    #     floating_ip_address: "{{ found_floating_ips.openstack_floating_ips[0].floating_ip_address }}"
    #   when: found_floating_ips.openstack_floating_ips is defined and found_floating_ips.openstack_floating_ips | length > 0

    # - name: Find security group by name
    #   openstack.cloud.security_group_info:
    #     cloud: kakao-cloud
    #     name: "my_security_group"
    #   register: found_security_groups

    # - name: Delete security group if exists
    #   openstack.cloud.security_group:
    #     cloud: kakao-cloud
    #     state: absent
    #     security_group: "{{ found_security_groups.openstack_security_groups[0].id }}"
    #   when: found_security_groups.openstack_security_groups is defined and found_security_groups.openstack_security_groups | length > 0


    - name: Delete key pair
      openstack.cloud.keypair:
        cloud: kakao-cloud
        state: absent
        name: "{{ vm.key_pair }}"
