- name: Clone kic-library-react repository
  git:
    repo: 'https://github.com/minjun0707/kakaocloud-library'
    dest: './kakaocloud-library'
    force: yes

- name: Run install-requirements.sh
  command: bash install-requirements.sh
  args:
    chdir: './kakaocloud-library'

# - name: Export environment variables
#   shell: |
#     export PROFILE={{ app_env.PROFILE }}
#     export MYSQL_HOST={{ app_env.MYSQL_HOST }}
#     export DB_NAME={{ app_env.DB_NAME }}
#     export DB_USERNAME={{ app_env.DB_USERNAME }}
#     export DB_PASSWORD={{ app_env.DB_PASSWORD }}
#     export REDIS_HOST={{ app_env.REDIS_HOST }}
#     export REDIS_PORT={{ app_env.REDIS_PORT }}
#   args:
#     executable: /bin/bash
#   become: yes

- name: Clone kic-library-react repository
  git:
    repo: 'https://github.com/minjun0707/kakaocloud-library'
    dest: './kakaocloud-library'
    force: yes

- name: Run install-requirements.sh
  command: bash install-requirements.sh
  args:
    chdir: './kakaocloud-library'

- name: Set environment variables
  set_fact:
    app_env:
      PROFILE: 'local'
      MYSQL_HOST: 'localhost'
      DB_NAME: 'library'
      DB_USERNAME: 'user'
      DB_PASSWORD: 'password'
      REDIS_HOST: 'localhost'
      REDIS_PORT: '6379'

- name: Stop and remove all running Docker containers
  shell: |
    docker ps -q | xargs -r docker stop
    docker ps -a -q | xargs -r docker rm

- name: Build Docker image for server
  shell: >
    docker build -q -f /home/ubuntu/kakaocloud-library/server/deploy/Dockerfile /home/ubuntu/kakaocloud-library/server -t kakaocloud-library-server
  register: build_server_result

- name: Run Docker container for server
  shell: |
    docker run -it \
    -e PROFILE={{ app_env.PROFILE }} \
    -e MYSQL_HOST={{ app_env.MYSQL_HOST }} \
    -e DB_NAME={{ app_env.DB_NAME }} \
    -e DB_USERNAME={{ app_env.DB_USERNAME }} \
    -e DB_PASSWORD={{ app_env.DB_PASSWORD }} \
    -e REDIS_HOST={{ app_env.REDIS_HOST }} \
    -e REDIS_PORT={{ app_env.REDIS_PORT }} \
    -p 8080:8080 \
    --name kakaocloud-library-server -d \
    kakaocloud-library-server
  when: build_server_result is succeeded
  become: yes

