- name: Clone kic-library-react repository
  git:
    repo: 'https://github.com/minjun0707/kakaocloud-library'
    dest: './kakaocloud-library'
    force: yes

- name: Run install-requirements.sh
  command: bash install-requirements.sh
  args:
    chdir: './kakaocloud-library'

# - name: Export SERVER_ENDPOINT environment variable
#   ansible.builtin.shell: echo "export SERVER_ENDPOINT="http://{app_fixed_ip}:8080"" >> /etc/environment
#   become: yes

- name: Stop and remove all running Docker containers
  shell: |
    docker ps -q | xargs -r docker stop
    docker ps -a -q | xargs -r docker rm

- name: Build Docker image
  shell: >
    sudo docker build -q -f /home/ubuntu/kakaocloud-library/client/deploy/Dockerfile /home/ubuntu/kakaocloud-library/client -t kakaocloud-library-client
  register: build_client_result

- name: Run Docker container for client
  shell: >
    docker run -it \
    -e SERVER_ENDPOINT=http://{{app_floating_ip}}:8080 \
    -p 80:80 -p 443:443 \
    --name kakaocloud-library-client -d \
    kakaocloud-library-client
  when: build_client_result is succeeded
  become: yes


# sudo docker run -it \
#   -e SERVER_ENDPOINT=${SERVER_ENDPOINT} \
# -p 80:80 -p 443:443 \
# --name kakaocloud-library-client -d \
# $(sudo docker build -q -f /home/ubuntu/kakaocloud-library/client/deploy/Dockerfile /home/ubuntu/kakaocloud-library/client -t kakaocloud-library-client)